# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f1b1c5a7840da2b593aa78be0092e76f00c17e24f3a383a3cb9005e4bea678611567f03a5ee3670dde7194262b88ba54b546bb4089819f8dea2d517ef916a8

test:
  secret_key_base: bd2bf7ccef503e79e14bd267fadf1a33919d715b25810a8f16068d7f54b4d1dfcef84ec7704c33823d79be5b873475da7f6b9b9ae0ec4453e305de92e0a3edfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
